import { getCollection } from "astro:content";
import { parseDocId, t, type Locale } from "@i18n/index";

export interface DocEntry {
  id: string;
  data: {
    title: string;
    description?: string;
    category?: string;
    tags?: string[];
    created?: Date;
    order?: number;
    draft?: boolean;
  };
  render: () => Promise<{ Content: astroHTML.JSX.Element }>;
}

/**
 * Returns all published docs in the given locale.
 * Docs without `.ja` suffix are treated as `zh`; docs with `.ja` suffix are `ja`.
 */
export async function getPublishedDocs(locale: Locale): Promise<DocEntry[]> {
  const docs = await getCollection("docs");
  return docs
    .filter((doc) => !doc.data.draft)
    .filter((doc) => parseDocId(doc.id).locale === locale)
    .sort(
      (a, b) => (a.data.order ?? 999) - (b.data.order ?? 999),
    ) as unknown as DocEntry[];
}

/**
 * Recursive navigation tree node, consumed by Sidebar and the category grid.
 *
 * - Directory nodes are produced for every intermediate path segment.
 * - A directory becomes clickable when its folder ships an `index.mdx`: we hoist
 *   that doc's title/order onto the directory node and strip the leaf child so
 *   it is not rendered twice.
 * - `href` is the canonical URL (no trailing `/index`): `foo/index.mdx` →
 *   `${base}${localePrefix}foo`. The legacy `/foo/index` route is still
 *   generated by `getStaticPaths` for backward compatibility, but sidebar
 *   and home-card links always point at canonical.
 */
export interface NavNode {
  /** Path segment at this level, e.g. "api-communication". */
  segment: string;
  /** Full slug path from docs root, e.g. "web-backend/api-communication". */
  path: string;
  /** Display label (already i18n/frontmatter resolved). */
  label: string;
  /** Click target. Absent for directories without an `index.mdx`. */
  href?: string;
  /** Sort key (frontmatter.order, falls back to 999). */
  order: number;
  /** Child nodes (undefined for leaves). */
  children?: NavNode[];
  /** Whether this node represents a directory (vs a document leaf). */
  isDirectory: boolean;
}

const DEFAULT_ORDER = 999;

/**
 * Canonicalizes a docs slug by stripping a trailing `/index` segment, so that
 * `foo/index.mdx` resolves to the canonical URL `/foo` instead of `/foo/index`.
 *
 * Rules:
 * - Only strips when the slug contains a `/` AND ends with `/index` (i.e. an
 *   intermediate or leaf directory's index doc). Bare `index` is left as-is.
 * - The strip is anchored to the final segment so docs named `indexing.mdx`,
 *   `index-notes.mdx`, etc. are not mis-stripped.
 *
 * Examples:
 *   canonicalizeSlug("foo/index")            === "foo"
 *   canonicalizeSlug("foo/bar/index")        === "foo/bar"
 *   canonicalizeSlug("index")                === "index"   // bare, preserved
 *   canonicalizeSlug("foo")                  === "foo"     // no trailing /index
 *   canonicalizeSlug("foo/indexing")         === "foo/indexing"
 *   canonicalizeSlug("foo/index-notes")      === "foo/index-notes"
 *   canonicalizeSlug("foo/bar/baz")          === "foo/bar/baz"
 */
export function canonicalizeSlug(slug: string): string {
  if (typeof slug !== "string" || slug.length === 0) return slug;
  if (slug.includes("/") && slug.endsWith("/index")) {
    return slug.slice(0, -"/index".length);
  }
  return slug;
}

/**
 * Hard cap on navigation depth (number of layers, L1–L4).
 *
 * NOTE: This is the count of layers — not a zero-based index. The recursive
 * `depth` variable used in `NavItem.astro` starts from 0, so the equivalent
 * runtime guard there is `depth >= MAX_NAV_DEPTH` (i.e. `depth >= 4`).
 *
 * Docs deeper than L4 are flattened to L4 by `getNavTree` with a
 * `console.warn` (see L5+ truncation block below).
 */
export const MAX_NAV_DEPTH = 4;

/**
 * Normalizes an Astro `currentPath` (i.e. `Astro.url.pathname`) into the
 * `NavNode.path` coordinate system used by the nav tree.
 *
 * The nav tree's `path` is a docs-root-relative slug WITHOUT base prefix,
 * locale prefix, leading/trailing slashes, or trailing `/index` segment.
 * This helper undoes all of those wrappings so callers can do plain string
 * equality against `NavNode.path`.
 *
 * Examples (base = "/venomous-study/"):
 *   ("/venomous-study/", "/venomous-study/", "")        -> ""
 *   ("/venomous-study/ja/", "/venomous-study/", "ja/")  -> ""
 *   ("/venomous-study/ja",  "/venomous-study/", "ja/")  -> ""   (no trailing slash tolerated)
 *   ("/", "/", "")                                       -> ""
 *   ("/venomous-study/web-backend/api-communication/index", "/venomous-study/", "")
 *       -> "web-backend/api-communication"
 *   ("/venomous-study/web-backend/api-communication/graphql/index", "/venomous-study/", "")
 *       -> "web-backend/api-communication/graphql"
 *   ("/venomous-study/ja/web-backend/api-communication/graphql/schema-and-resolver", "/venomous-study/", "ja/")
 *       -> "web-backend/api-communication/graphql/schema-and-resolver"
 *   ("/venomous-study/backend/intro", "/venomous-study/", "")
 *       -> "backend/intro"
 *
 * The trailing `/index` strip uses an anchored match (`/\/index$/`) so docs
 * named `indexing.mdx`, `index-notes.mdx`, etc. are NOT mis-stripped.
 */
export function toNavPath(
  currentPath: string,
  base: string,
  localePrefix: string,
): string {
  if (typeof currentPath !== "string" || currentPath.length === 0) return "";

  // Tolerate a missing trailing slash on the bare base (e.g. `/venomous-study`
  // when base is `/venomous-study/`). Append a `/` so `startsWith(base)` works
  // uniformly. This is a defensive fallback; Astro normally normalizes URLs.
  let path = currentPath;
  if (base.length > 1 && base.endsWith("/") && path + "/" === base) {
    path = base;
  }

  // Strip base prefix.
  if (base.length > 0 && path.startsWith(base)) {
    path = path.slice(base.length);
  }

  // Strip leading slash(es) defensively.
  path = path.replace(/^\/+/, "");

  // Strip locale prefix (e.g. "ja/"). Also tolerate the bare locale form
  // without trailing slash (e.g. "ja") which can occur if a base-stripped
  // path equals exactly the locale code.
  if (localePrefix.length > 0) {
    if (path.startsWith(localePrefix)) {
      path = path.slice(localePrefix.length);
    } else if (path === localePrefix.replace(/\/$/, "")) {
      path = "";
    }
  }

  // Strip trailing slash(es).
  path = path.replace(/\/+$/, "");

  // Strip trailing `/index` (anchored — must be a whole segment).
  path = path.replace(/\/index$/, "");

  return path;
}

/**
 * Returns the `l1/l2/l3` path string of the L3 ancestor of the current page,
 * when the current page sits at L3 or deeper (i.e. `navPath` has ≥ 3 segments).
 *
 * The threshold is `< 3` → `null` so that L3 index pages (canonical
 * `/l1/l2/l3`) AND L4 leaf pages (`/l1/l2/l3/leaf`) both expand the same L3
 * subtree, giving a consistent "inside this technology stack, see all pages"
 * experience. Homepage, L1 pages, and L2 index pages (< 3 segments) return
 * `null` so every L3 stays collapsed.
 *
 * For an L3 index page like `/web-backend/api-communication/graphql`, the
 * normalized navPath is `web-backend/api-communication/graphql` → returns
 * `"web-backend/api-communication/graphql"` (3-segment match).
 */
export function getCurrentL3Path(navPath: string): string | null {
  const segments = navPath.split("/").filter((s) => s.length > 0);
  if (segments.length < 3) return null;
  return segments.slice(0, 3).join("/");
}

interface MutableNode {
  segment: string;
  path: string;
  label: string;
  href?: string;
  order: number;
  isDirectory: boolean;
  /** Keyed by child segment for O(1) upsert. */
  children?: Map<string, MutableNode>;
}

function capitalize(s: string): string {
  return s.length === 0 ? s : s.charAt(0).toUpperCase() + s.slice(1);
}

/**
 * Resolves the display label for a directory node.
 * - Top-level (depth 0): dictionary lookup, then capitalized segment.
 * - Deeper:  index.mdx title (already applied by caller if present), else
 *            dictionary lookup, else raw segment.
 */
function directoryLabel(
  segment: string,
  locale: Locale,
  depth: number,
  indexTitle?: string,
): string {
  if (indexTitle && indexTitle.length > 0) return indexTitle;
  const key = `categories.${segment}`;
  const translated = t(key, locale);
  if (translated !== key) return translated;
  return depth === 0 ? capitalize(segment) : segment;
}

function ensureDirectory(
  parentChildren: Map<string, MutableNode>,
  segment: string,
  parentPath: string,
  depth: number,
  locale: Locale,
): MutableNode {
  const existing = parentChildren.get(segment);
  if (existing) return existing;
  const path = parentPath ? `${parentPath}/${segment}` : segment;
  const node: MutableNode = {
    segment,
    path,
    label: directoryLabel(segment, locale, depth),
    order: DEFAULT_ORDER,
    isDirectory: true,
    children: new Map(),
  };
  parentChildren.set(segment, node);
  return node;
}

function sortAndFreeze(node: MutableNode): NavNode {
  const childMap = node.children;
  let children: NavNode[] | undefined;
  if (childMap && childMap.size > 0) {
    children = Array.from(childMap.values())
      .map(sortAndFreeze)
      .sort((a, b) => {
        if (a.order !== b.order) return a.order - b.order;
        return a.segment.localeCompare(b.segment);
      });
  }
  return {
    segment: node.segment,
    path: node.path,
    label: node.label,
    href: node.href,
    order: node.order,
    children,
    isDirectory: node.isDirectory,
  };
}

/**
 * Builds the recursive NavNode tree for the given locale. Consumed by
 * Sidebar.astro and the two home pages (index.astro, ja/index.astro).
 */
export async function getNavTree(locale: Locale): Promise<NavNode[]> {
  const docs = await getPublishedDocs(locale);
  const base = import.meta.env.BASE_URL;
  const localePrefix = locale === "zh" ? "" : "ja/";

  const roots = new Map<string, MutableNode>();
  // Tracks canonical slugs (after /index strip) already claimed by a doc.
  // If two docs canonicalize to the same slug (e.g. `foo.mdx` and
  // `foo/index.mdx` both map to `foo`), we warn and skip overwriting so the
  // first-seen owner wins — the second doc keeps its native route only.
  const canonicalOwners = new Map<string, string>();

  for (const doc of docs) {
    const { slug } = parseDocId(doc.id);
    const parts = slug.split("/").filter((p) => p.length > 0);

    // Root-level orphan doc (e.g. `docs/foo.mdx`) → virtual "uncategorized" group.
    let effectiveParts =
      parts.length === 1 ? ["uncategorized", parts[0]] : parts;

    // L5+ defense: depth cap is MAX_NAV_DEPTH layers (L1–L4). Anything deeper
    // gets flattened to L4 by keeping the first 3 ancestor segments + the
    // original leaf segment. The route URL itself is not mutated (callers
    // build href from the original `slug`), so the doc remains reachable.
    if (effectiveParts.length > MAX_NAV_DEPTH) {
      const truncated = [
        ...effectiveParts.slice(0, 3),
        effectiveParts[effectiveParts.length - 1],
      ];
      console.warn(
        `[getNavTree] L5+ doc detected (depth=${effectiveParts.length}); ` +
          `flattening to L4. original="${slug}" effective="${truncated.join("/")}"`,
      );
      effectiveParts = truncated;
    }

    const leafSegment = effectiveParts[effectiveParts.length - 1];
    const parentSegments = effectiveParts.slice(0, -1);
    // sidebar/home-card href uses canonical slug (no trailing `/index`), so
    // users always land on the canonical URL `/foo` rather than the
    // backward-compat `/foo/index` variant.
    const canonicalSlug = canonicalizeSlug(slug);
    const href = `${base}${localePrefix}${canonicalSlug}`;
    const order = doc.data.order ?? DEFAULT_ORDER;
    const isIndex = leafSegment === "index" && parentSegments.length > 0;

    // Canonical-slug collision guard. Warn once per conflict (first writer
    // wins); subsequent docs keep their own native route but cannot claim
    // the canonical slug.
    const existingOwner = canonicalOwners.get(canonicalSlug);
    if (existingOwner && existingOwner !== doc.id) {
      console.warn(
        `[getNavTree] canonical slug collision: "${canonicalSlug}" already ` +
          `claimed by "${existingOwner}"; skipping "${doc.id}". ` +
          `Rename one of the source files to disambiguate.`,
      );
    } else {
      canonicalOwners.set(canonicalSlug, doc.id);
    }

    // Walk/create parent directory chain.
    let currentChildren = roots;
    let currentPath = "";
    for (let depth = 0; depth < parentSegments.length; depth++) {
      const seg = parentSegments[depth];
      const dir = ensureDirectory(
        currentChildren,
        seg,
        currentPath,
        depth,
        locale,
      );
      currentPath = dir.path;
      if (!dir.children) dir.children = new Map();
      currentChildren = dir.children;
    }

    if (isIndex) {
      // Hoist the `{dir}/index.mdx` onto its owning directory node.
      const parentPath = parentSegments.slice(0, -1).join("/");
      const ownerSegment = parentSegments[parentSegments.length - 1];
      // Walk back to owner's children map (one level up from `currentChildren`).
      // Since `currentChildren` is the owner's children map, we need the owner
      // itself to patch label/href/order. Re-resolve via a second pass:
      let ownerParentChildren = roots;
      for (let i = 0; i < parentSegments.length - 1; i++) {
        const parentDir = ownerParentChildren.get(parentSegments[i]);
        if (!parentDir || !parentDir.children) break;
        ownerParentChildren = parentDir.children;
      }
      const owner = ownerParentChildren.get(ownerSegment);
      if (owner) {
        owner.href = href;
        owner.order = order;
        owner.label = directoryLabel(
          owner.segment,
          locale,
          parentSegments.length - 1,
          doc.data.title,
        );
      }
      // `parentPath` retained for clarity; no further use.
      void parentPath;
    } else {
      // Attach leaf doc node.
      const leafNode: MutableNode = {
        segment: leafSegment,
        path: currentPath ? `${currentPath}/${leafSegment}` : leafSegment,
        label: doc.data.title,
        href,
        order,
        isDirectory: false,
      };
      // Detect collision: only meaningful when the leaf was placed by the
      // L5+ truncation pass (parts.length > MAX_NAV_DEPTH) and the target
      // segment is already taken. Distinguish "two truncated leaves clash"
      // vs "truncated leaf overrides an existing native L4 doc".
      if (parts.length > MAX_NAV_DEPTH && currentChildren.has(leafSegment)) {
        const prior = currentChildren.get(leafSegment);
        const priorKind = prior && prior.isDirectory ? "directory" : "doc";
        console.warn(
          `[getNavTree] L5+ truncation segment collision at "${leafNode.path}" ` +
            `(original slug="${slug}"): overwriting existing ${priorKind} node. ` +
            `Rename one of the source files to disambiguate.`,
        );
      }
      currentChildren.set(leafSegment, leafNode);
    }
  }

  return Array.from(roots.values())
    .map(sortAndFreeze)
    .sort((a, b) => {
      if (a.order !== b.order) return a.order - b.order;
      return a.segment.localeCompare(b.segment);
    });
}
